export const GET_HOME_MENUS = "GET_HOME_MENUS";
export const GET_RECOMMENDED_ALBUMS = "GET_RECOMMENDED_ALBUMS";
export const GET_TOP_SONGS = "GET_TOP_SONGS";
export const GET_RECENT_PLAYLIST = "GET_RECENT_PLAYLIST";
export const GET_CURRENT_SONG = "GET_CURRENT_SONG";
export const SET_CURRENT_SONG = "SET_CURRENT_SONG";
export const ADD_USER = "ADD_USER";
export const SET_USERS = "SET_USERS";
export const DELETE_USER = "DELETE_USER";
export const GET_ADMIN_SONGS = "GET_ADMIN_SONGS";
export const GET_ADMIN_ARTISTS = "GET_ADMIN_ARTISTS";
export const TIME = {
    TODAY: 'TODAY',
    WEEK: 'WEEK',
    MONTH: 'MONTH'
}