export const GET_HOME_MENUS = "GET_HOME_MENUS";
export const GET_RECOMMENDED_ALBUMS = "GET_RECOMMENDED_ALBUMS";
export const GET_TOP_SONGS = "GET_TOP_SONGS";
export const GET_RECENT_PLAYLIST = "GET_RECENT_PLAYLIST";
export const GET_CURRENT_SONG = "GET_CURRENT_SONG";
export const TIME = {
    TODAY: 'TODAY',
    WEEK: 'WEEK',
    MONTH: 'MONTH'
}